language: r
r: bioc-devel
cache: packages
warnings_are_errors: false
bioc_packages:
  - testthat
  - DESeq2
  - limma
r_packages:
  - covr
  - S4Vectors
after_success:
  - Rscript -e 'library(covr); codecov()'